application/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.contrib import admin
from . import views
from django.urls import path, re_path
from django.contrib import admin
from django.urls import path, include
from .views import SignUpView

app_name = 'application'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    re_path(r'^home/$', views.home, name='home'),
    path('', TemplateView.as_view(template_name="home.html"), name='home'),
    path('match_list/', views.match_list, name='match_list'),
    path('match_list_error/', views.match_list_error, name='match_list_error'),
    path('match/<int:pk>/edit/', views.match_edit, name='match_edit'),
    path('match/create/', views.match_new, name='match_new'),
    path('match/<int:pk>/delete/', views.match_delete, name='match_delete'),
    path('team/create/', views.team_new, name='team_new'),
    path('team_list', views.team_list, name='team_list'),
    path('my_team_list', views.my_team_list, name='my_team_list'),
    path('team/<int:pk>/edit/', views.team_edit, name='team_edit'),
    path('team/<int:pk>/delete/', views.team_delete, name='team_delete'),
    path('player_list', views.player_list, name='player_list'),
    path('player/<int:pk>/edit/', views.player_edit, name='player_edit'),
    path('coach/player/<int:pk>/edit/', views.coach_player_edit, name='coach_player_edit'),
    path('player/<int:pk>/delete/', views.player_delete, name='player_delete'),
    path('player/create/', views.player_new, name='player_new'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('report_scores/', views.report_scores_list, name='report_scores_list'),
    path('report_scores/search', views.report_scores_by_search, name='report_scores_by_search'),
    path('report_scores/search/<int:pk>/', views.report_scores_by_search_edit, name='report_scores_by_search_edit'),
    #path('stats/', views.stats, name='stats'),
    path('technical_manual/', views.technical_manual, name='technical_manual'),
    path('player_by_team_list/', views.player_by_team_list, name='player_by_team_list'),

]

tournamentapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.urls import path, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('report_builder/', include('report_builder.urls')),
    path('', include('application.urls')),
    path('', include('django.contrib.auth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

application/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm


class MatchForm(forms.ModelForm):
    start_time = forms.CharField(
        widget=forms.TextInput(
            attrs={'type': 'time'}
        )
    )
    start_date = forms.CharField(
        widget=forms.TextInput(
            attrs={'type': 'date'}
        )
    )
    class Meta:
        model = Match
        fields = (
            'home_team',
            'guest_team',
            'field',
            'referee',
            'referee_uid',
            'start_time',
            'start_date',
            'home_team_score',
            'guest_team_score',
            'match_notes',
            'match_players_goals_scored',)


class ReportForm(forms.ModelForm):
    class Meta:
        model = Match
        fields = (
            'id',
            'home_team_score',
            'guest_team_score',
            'match_notes',
            'match_players_goals_scored',)


class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = (
            'id',
            'school',
            'name',
            'coach_uid',
            'coach',
            'coach_email',
            'coach_phone',)


class PlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = (
            'team',
            'first_name',
            'last_name',
            'position')

class CoachPlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = (
            'first_name',
            'last_name',
            'position')

class ModelForm(forms.ModelForm):
    start_time = forms.CharField(
        widget=forms.TextInput(
            attrs={'type': 'time'}
        )
    )
    start_date = forms.CharField(
        widget=forms.TextInput(
            attrs={'type': 'date'}
        )
    )

    class Meta:
        model = Match
        fields = (
            'home_team',
            'guest_team',
            'field',
            'referee',
            'referee_uid',
            'start_time',
            'start_date',
            'home_team_score',
            'guest_team_score',
            'match_notes',
            'match_players_goals_scored',)


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=254)
    username = forms.CharField(min_length=3, max_length=30, required=True)
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password Again', widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]

application/views.py
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.contrib.auth.models import Group
import application
from .filters import *
from .forms import *
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
import django_filters
from .models import *
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth import logout as bruh
from django.db import connection
from django.db.models import Q


def home(request):
    return render(request, 'home.html', )


def get_matches():
    return Match.objects.filter(created_date__lte=timezone.now())


def match_list_error(request):
    matches = get_matches().order_by('start_date', )
    return render(request, 'match_list_error.html',
                  {'matches': matches})


def match_list(request):
    matches = get_matches().order_by('start_date', )

    # test = Group.objects.values(name='Referee_Group').exists()
    # Group.objects.filter(user=request.user)

    return render(request, 'match_list.html',
                  {'matches': matches})


@login_required
def match_edit(request, pk):
    match = get_object_or_404(Match, pk=pk)
    if request.method == "POST":
        form = MatchForm(request.POST, instance=match)
        firststep = form.save(commit=False)
        if form.is_valid():
            try:

                # check if field is same
                results = Match.objects.filter(start_date=firststep.start_date, field=firststep.field, )
                integrity(results, firststep)

                # check if ref is same
                results = Match.objects.filter(start_date=firststep.start_date,
                                               referee=firststep.referee, )
                integrity(results, firststep)

                # check if teams are same first order
                results = Match.objects.filter(start_date=firststep.start_date,
                                               guest_team=firststep.guest_team,
                                               )
                integrity(results, firststep)

                # check if teams are same second order
                results = Match.objects.filter(start_date=firststep.start_date,
                                               home_team=firststep.guest_team)
                integrity(results, firststep)

                # check if teams are same third order
                results = Match.objects.filter(start_date=firststep.start_date,
                                               home_team=firststep.guest_team)
                integrity(results, firststep)

                # check if teams are same third order
                results = Match.objects.filter(start_date=firststep.start_date,
                                               home_team=firststep.guest_team)
                integrity(results, firststep)


            except ValueError:
                matches = get_matches().order_by('start_date')
                return render(request, 'match_list_error.html',
                              {'matches': matches})

            match.updated_date = timezone.now()
            match.save()
            matches = get_matches().order_by('start_date')
            return render(request, 'match_list.html',
                          {'matches': matches})

    else:
        form = MatchForm(instance=match)
        return render(request, 'match_edit.html', {'form': form})


@login_required
def match_new(request):
    if request.method == "POST":
        form = MatchForm(request.POST)
        firststep = form.save(commit=False)
        if form.is_valid():
            try:
                # check if field is same
                results = Match.objects.filter(start_date=firststep.start_date, field=firststep.field, )
                integrity(results, firststep)

                # check if ref is same
                results = Match.objects.filter(start_date=firststep.start_date,
                                               referee=firststep.referee, )
                integrity(results, firststep)

                # check if teams are same first order
                results = Match.objects.filter(start_date=firststep.start_date,
                                               guest_team=firststep.guest_team,
                                               )
                integrity(results, firststep)

                # check if teams are same second order
                results = Match.objects.filter(start_date=firststep.start_date,
                                               home_team=firststep.guest_team)
                integrity(results, firststep)

                # check if teams are same third order
                results = Match.objects.filter(start_date=firststep.start_date,
                                               home_team=firststep.guest_team)
                integrity(results, firststep)

                # check if teams are same third order
                results = Match.objects.filter(start_date=firststep.start_date,
                                               home_team=firststep.guest_team)
                integrity(results, firststep)

            except ValueError:
                matches = get_matches().order_by('start_date')
                return render(request, 'match_list_error.html',
                              {'matches': matches})
            match = form.save()
            match.updated_date = timezone.now()
            match.save()
            matches = get_matches().order_by('start_date')
            return render(request, 'match_list.html',
                          {'matches': matches})
    else:
        form = MatchForm()
    return render(request, 'match_new.html', {'form': form})

##ok try to do a check to see if the match ID's are the same between the form and the result
def integrity(results, firststep):
    errors = 0
    for obj in results:
        time = str(obj.start_time).split(":")
        print("Found start = ", time[0])
        print("Time input = ", (str(firststep.start_time).split(":")[0]))
        difference = int(str(firststep.start_time).split(":")[0]) - int(time[0])
        print("Difference = ", difference)
        print("Found ID = ", obj.id)
        print("Input ID = ", firststep.id)
        if 1 >= difference >= -1:
            errors += 1
            print("Errors: ", errors)
        if obj.id == firststep.id:
            errors -= 1
    if errors > 0:
        raise ValueError('Time constraints')


@login_required
def match_delete(request, pk):
    match = get_object_or_404(Match, pk=pk)
    match.delete()
    return redirect('application:match_list')


@login_required
def team_list(request):
    team = Team.objects.all()
    # team = Team.objects.filter(created_date__lte=timezone.now())

    return render(request, 'team_list.html',
                  {'teams': team})


@login_required
def my_team_list(request):
    team = Team.objects.all()
    team = Team.objects.filter(coach_uid=request.user)
    # school = School.objects.filter(team__coach_uid=request.user)
    return render(request, 'my_team_list.html',
                  {'teams': team})  # , {'school': school})


@login_required
def team_edit(request, pk):
    team = get_object_or_404(Team, pk=pk)
    if request.method == "POST":
        form = TeamForm(request.POST, instance=team)
        if form.is_valid():
            team = form.save()

            team.updated_date = timezone.now()
            team.save()
            if request.user.is_superuser:
                teams = Team.objects.filter(created_date__lte=timezone.now())
            else:
                teams = Team.objects.filter(coach_uid=request.user)
            return render(request, 'team_list.html', {'teams': teams})
    else:
        print("else")
        form = TeamForm(instance=team)
    return render(request, 'team_edit.html', {'form': form})


@login_required
def team_new(request):
    if request.user.is_superuser:
        if request.method == "POST":
            form = TeamForm(request.POST)
            if form.is_valid():
                team = form.save()
                team.updated_date = timezone.now()
                team.save()
                teams = Team.objects.filter(created_date__lte=timezone.now())
                return render(request, 'team_list.html', {'teams': teams})
        else:
            # print("else")
            form = TeamForm()
            return render(request, 'team_new.html', {'form': form})
    else:
        return render(request, 'home.html', )


@login_required
def team_delete(request, pk):
    if request.user.is_superuser:
        team = get_object_or_404(Team, pk=pk)
        team.delete()
        return redirect('application:team_list')
    else:
        return render(request, 'home.html', )


@login_required
def player_new(request):
    if request.method == "POST":
        form = PlayerForm(request.POST)
        if form.is_valid():
            player = form.save(commit=False)
            player.created_date = timezone.now()
            player.save()
            if request.user.is_superuser:
                players = Player.objects.all()
            else:
                players = Player.objects.filter(team__coach_uid=request.user)
            return render(request, 'player_list.html',
                          {'players': players})
    else:
        form = PlayerForm()
        # print("Else")
    return render(request, 'player_new.html', {'form': form})


@login_required
def player_delete(request, pk):
    player = get_object_or_404(Player, pk=pk)
    player.delete()
    return redirect('application:player_list')


@login_required
def player_new(request):
    if request.method == "POST":
        form = PlayerForm(request.POST)
        if form.is_valid():
            player = form.save(commit=False)
            player.created_date = timezone.now()
            player.save()

application/templates/base.html
{% load static %}
{% load auth_extras %}

<html lang="en">
<head>
    <title>Missouri Soccer Tournament</title>

    <link rel="icon" type="image/jpg" href="{% static 'unnamed.jpg' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
            background-color: #0f0f0f;
            color: #ffffff;
        }
        navbar-inverse .navbar-nav > li > a {
            color: #ffffff;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
        }
        .collapsible {
          background-color: #777;
          color: white;
          cursor: pointer;
          padding: 18px;
          width: 100%;
          border: none;
          text-align: left;
          outline: none;
          font-size: 15px;
          margin-bottom: 10px;
        }

        .active, .collapsible:hover {
          background-color: #555;
        }

        .collapsiblecontent {
          padding: 0 18px;
          display: none;
          overflow: hidden;
          background-color: #f1f1f1;
          margin-top: -10px;
          margin-bottom: 10px;
        }
        .collapsiblecontent p {
            font-size: 15px;
        }
        /* Responsive columns - one column layout (vertical) on small screens */
        @media screen and (max-width: 600px) {
          .fart {
            width: 100%;
            display: block;
            margin-bottom: 20px;}  }
        h2 {
        text-align: center;
        padding: 10px;
        }
        h3 {
        text-align: center;
        padding: 10px;
        }
        h1 {
        text-align: center;
        padding: 10px;
        }
        .contentboxes {
        margin: auto;
        position: relative;
        width: 50%
        }

        .boxtitles {
        text-align: center;
        }

        .content {
        margin: 20px;
        padding: 10px;
        position: relative;
        }
        .button {
            display: block;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }
        .cardbody{
            border-style: solid;
            border-width: 3px;
            border-color: black;
            width: 25%;
            padding: 5%;
            margin: auto;


        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }

        body {
        margin:0;
        padding:0;
        font-family:helvetica, sans-serif;
        }

        h1, h2, h3, h4, h5 , h6 {
            font-family: 'Ubuntu', sans-serif; font-weight:normal;
        }

        a {
            text-decoration:none;
            color:#5993bb;
        }

        a:hover {
            color:#77b6e2;
        }

        a.button, input[type="submit"] {
            color:#fff;
            background:#5993bb;
            border-radius:4px;
            padding:10px 20px;
            font-size:14px;
            border:0;
        }

        a.button.light {
            color:#666;
            background:#ededed;
        }

        .text-left {
            text-align:left;
        }

        .text-right {
            text-align:right;
        }

        table {
            width:100%;
            border-spacing:0;
            border-collapse: collapse;
        }

        table th, table td {
            text-align:left;
            font-size:14px;
            padding:10px;
            margin:0;
        }

        tbody tr:nth-child(odd) {
            background:#efefef;
        }

        tbody tr.subtotal {
            background:#ccc;
        }

        thead th, tbody tr.total {
            background:#5993bb;
            color:#fff;
            font-weight:bold;
        }

        table.cart {
            margin-bottom:40px;
        }

        table.cart img {
            width:180px;
        }

        tbody td.num {
            text-align:right;
        }

        td input[type="submit"] {
            font-size:12px;
            padding:4px 10px;
        }

        form p label, form p input {
            float:left;
            clear:both;
        }

        form p label {
            font-size:14px;
            padding-bottom:4px;
        }

        form p input {
            width:300px;
            font-size:13px;
            margin-bottom:10px;
            padding:10px 12px;
            border:0;
            background:#efefef;
            color:#666;
            border-radius:4px;
        }

        ul.errorlist {
           float:left;
           color:#ff0000;
           clear:both;
           font-size:13px;
           margin:0;
           padding:0;
        }


        #header {
            padding:10px 100px;
            font-size:18px;
            overflow:auto;
        }

        #subheader {
            background:#ececec;
            color:#444;
            padding:15px 100px;
            overflow:auto;
        }

        #header .logo {
            font-family: 'Ubuntu', sans-serif;
            float:left;
            color:#333;
            font-size:22px;
            margin-right:10%;
        }

        #subheader .cart {
            float:right;
            padding-top:4px;
        }

        .content {
            padding:0px;
            overflow:hidden;
        }

        #sidebar {
            width:220px;
            padding:30px 20px 0 0;
            float:left;
        }

        #sidebar ul{
            margin:0;
            padding:0;
        }

        #sidebar ul li {
            margin:0;
            list-style:none;
            padding:10px 14px;
        }

        #sidebar ul li a {
            display:block;
        }

        #sidebar ul li.selected {
            background:#5993bb;
            border-radius:4px;
        }

        #sidebar ul li.selected a {
            color:#fff;
        }

        #main {
            float:left;
            width: 96%;
            margin-right:-220px;
            overflow:hidden;
        }
    </style>
</head>
<body id="app-layout">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand"  href="{% url 'application:home' %}">
                Home
            </a>
        </div>

        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">

                <li><a href="{% url 'application:match_list' %}">Matches</a></li>
                <li><a href="{% url 'application:team_list' %}">Teams</a></li>
                <li><a href="{% url 'application:player_list' %}">Players</a></li>
                {% if request.user|has_group:"Referee" %}
                <li><a href="{% url 'application:report_scores_by_search' %}">Report Score</a></li>
                {% endif %}
            {% if request.user|has_group:"Coach" %}
            <li><a href="{% url 'application:my_team_list' %}">My Team</a></li>
            {% endif %}

            {% if user.is_superuser or request.user|has_group:"Referee" or request.user|has_group:"Coach" %}
                <li><a href="{% url 'application:technical_manual' %}">Help</a></li>
            {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    {% if request.user|has_group:"Referee" or request.user|has_group:"Coach" %}
               <li><a><i class="fa fa-btn fa-sign-out"></i>Logged in as a: {% for group in user.groups.all %}
                                                                             {{ group }}
                                                                            {% endfor %}
                                                                             </a></li>
                    {% endif %}
                    {% if user.is_superuser %}
                        <li><a><i class="fa fa-btn fa-sign-out"></i>Administrator Access</a></li>
                        {% endif %}
                <li><a><i class="fa fa-btn fa-sign-out"></i> Welcome, {{request.user}}!</a></li>
                <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                {% else %}
                <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="content">
        {% block content %}


        {% endblock %}
    </div>
</body>
</html>

application/templates/match_delete.html
{% block body_block %}
    <h1>Delete {{ match.pk }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="w3-button w3-round w3-red" value="Delete">
        <a href="{% url 'application:match_list' pk=match.pk %} ">Cancel</a>
    </form>

{% endblock %}

application/templates/match_list.html
{% extends 'base.html' %}
{% load auth_extras %}
{% load static %}
{% block content %}
    <div style="background-color: #2a2a2a2a; padding: 10px;">
        <h1>Matches List</h1>
    </div>
        <div style="margin-bottom: 10px">

    </div>
{% for match in matches %}
    <button type="button" class="collapsible" style="text-align: center; font-size: 20px">
        Match #{{ match.pk }}: {{match.home_team}} vs. {{ match.guest_team }}, {{ match.start_date }} {{ match.start_time }}</button>
    <div class="collapsiblecontent">
        <p>
            Match #: {{ match.pk }}<br>
            Home Team: {{match.home_team}}<br>
            Guest Team: {{match.guest_team}}<br>
            Field: {{match.field}}<br>
            Referee: {{match.referee}}<br>
            Date: {{match.start_time}}, {{ match.start_date }}<br>
            Score: {{match.home_team_score}} - {{match.guest_team_score}}<br>
            Notes: {{match.match_notes}}<br>
            Goals Scored: {{match.match_players_goals_scored}}<br>
                    {% if user.is_superuser or request.user|has_group:"Referee" %}
                    <a href="{% url 'application:match_edit' pk=match.id %}" class="w3-button w3-round w3-orange">Edit</a>
                    <a href="{% url 'application:match_delete' pk=match.pk%}"
                        onclick="return confirm('Are you sure you want to delete Match {{ match.id }}?')"
                                class="w3-button w3-round w3-red">Delete</a>
                    {% endif %}
        </p>
    </div>
{% endfor %}
            <div style="margin-left: auto; margin-right: auto">
                {% if user.is_superuser or request.user|has_group:"Referee"%}
                <a href="{% url 'application:match_new' %}"><span
                    class="w3-button w3-round w3-blue">Add Match</span></a>
                {% endif %}
        </div>

<script>
    var coll = document.getElementsByClassName("collapsible");
    var i;

    for (i = 0; i < coll.length; i++) {
      coll[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var content = this.nextElementSibling;
        if (content.style.display === "block") {
          content.style.display = "none";
        } else {
          content.style.display = "block";
        }
      });
    }
</script>
{% endblock %}

application/templates/my_team_list.html
{% extends 'base.html' %}
{% load static %}
{% load auth_extras %}
{% block content %}

    <div style="background-color: #2a2a2a2a; padding: 10px;">
        <h1>{{request.user}}'s Team</h1>
    </div>
    <div style="margin-bottom: 10px">

    </div>
{% for team in teams %}
    <button type="button" class="collapsible" style="text-align: center; font-size: 20px">{{ team.name}}</button>
    <div class="collapsiblecontent">
        <p>
            Team ID: {{team.id}} <br>
            Name: {{ team.name }} <br>
            School: {{team.school}} <br>
            Coach: {{team.coach}} <br>
            Coach Email: {{ team.coach_email }} <br>
            Coach Phone: {{ team.coach_phone}} <br>

            <a href="{% url 'application:player_by_team_list' %}" class="w3-button w3-round w3-indigo">View Players</a>



        </p>
        {% if user.is_superuser or request.user|has_group:"Coach" %}
            <a href="{% url 'application:team_edit' pk=team.pk %}" class="w3-button w3-round w3-orange">Edit</a>

            {% endif %}
     </div>
{% endfor %}



<script>
    var coll = document.getElementsByClassName("collapsible");
    var i;

    for (i = 0; i < coll.length; i++) {
      coll[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var content = this.nextElementSibling;
        if (content.style.display === "block") {
          content.style.display = "none";
        } else {
          content.style.display = "block";
        }
      });
    }
</script>
{% endblock %}
   

application/templates/player_list.html
{% extends 'base.html' %}
{% load auth_extras %}
{% load static %}
{% block content %}
    <div style="background-color: #2a2a2a2a; padding: 10px;">
        <h1>All Players List</h1>
    </div>
    <div style="margin-bottom: 10px">

    </div>
{% for player in players %}
    <button type="button" class="collapsible" style="text-align: center; font-size: 20px">{{ player.last_name }}, {{player.first_name}}</button>
    <div class="collapsiblecontent">
        <p>
            First Name: {{player.first_name}}<br>
            Last Name: {{player.last_name}}<br>
            Position: {{player.position}}<br>
            Assigned Team: {{player.team}}
        </p>
        {% if user.is_superuser %}
        <a href="{% url 'application:player_edit' pk=player.pk %}" class="w3-button w3-round w3-orange">Edit</a>
        <a href="{% url 'application:player_delete' pk=player.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="w3-button w3-round w3-red">Delete</a>
        {% endif %}

    </div>
{% endfor %}
    {% if user.is_superuser %}
<div style="margin-left: auto; margin-right: auto">
    <a href="{% url 'application:player_new' %}"><span
                    class="w3-button w3-round w3-blue">Add Player</span></a>
    {% endif %}
</div>
<script>
    var coll = document.getElementsByClassName("collapsible");
    var i;

    for (i = 0; i < coll.length; i++) {
      coll[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var content = this.nextElementSibling;
        if (content.style.display === "block") {
          content.style.display = "none";
        } else {
          content.style.display = "block";
        }
      });
    }
</script>
{% endblock %}
   